### ISSUE TITLE
Put the synopsis on the "index" manpages

### ISSUE THREAD

**Issue by richsalz** [openssl/web#101]
The manual 'index' pages such as https://www.openssl.org/docs/man1.1.1/man1/, just do the equivalent of a directory listing, showing filename and meta-data.  As suggested by Jakob Bohm on the openssl-users mailing list:

>Consider at least including the one-line manpage summaries on the index
> pages (the ones displayed by the apropos command on POSIX systems).

**Comment by mattcaswell** [comment]
This is a really good idea! @levitte: any thoughts on how to implement this?

**Comment by levitte** [comment]
Yes.  See #102

**Comment by levitte** [comment]
You can currently see the result on https://beta.openssl.org/docs/

**Comment by mattcaswell** [comment]
I like it a lot!! Although it does highlight how bad some of those synopsis texts are.

**Comment by levitte** [comment]
That can be solved too, we all know how :wink:

**Comment by levitte** [comment]
#102 was merged a while ago.  Closing
