### ISSUE TITLE
New OpenSSL 3.0.0 documents have wrong rel=canonical

### ISSUE THREAD

**Issue by davidben** [openssl/web#117]
This two links below have `<link rel="canonical" href="https://www.openssl.org/">`, rather than the actual URL.
https://www.openssl.org/docs/OpenSSLStrategicArchitecture.html
https://www.openssl.org/docs/OpenSSL300Design.html

**Comment by mattcaswell** [comment]
This actually seems to be the case for lots of pages on the site. Not just those two.

**Comment by mattcaswell** [comment]
Seems to come from here:

https://github.com/openssl/web/blob/5c98cb9a57ad617454a721aa640cb096e09b5e7b/inc/head.shtml#L12

Which then gets included everywhere! Probably that line should just be deleted?
