### ISSUE TITLE
FIPS wiki page has inaccurate information

### ISSUE THREAD

**Issue by quanah** [openssl/web#130]
If you go to the [FIPS wiki page](https://wiki.openssl.org/index.php/FIPS_modules) it states that a new FIPS module will be available with the OpenSSL 1.1 series .  However, this is most definitely not the case, as the OpenSSL project has stated that the new FIPS module will instead be usable only with OpenSSL 3.0 and later.

```
A new validation effort is to develop and validate a new open source based cryptographic module was announced in July 2016[5]. This new module will be usable with OpenSSL release 1.1. It will provisionally be called OpenSSL FIPS Object Module 3.0. 
```

**Comment by mattcaswell** [comment]
I updated the text on the wiki.
