### ISSUE TITLE
PKCS #5 Version 2.1 is RFC 8018

### ISSUE THREAD

**Issue by EnigmaTriton** [openssl/web#155]
https://www.openssl.org/docs/standards.html page still refers to RFC 2898 for version 2.0.

Clearly not critical but worth updating.

**Comment by mattcaswell** [comment]
I'm not really sure how useful the list on that page really is. It's almost destined to always be out-of-date! It might be better to just remove it completely.

**Comment by EnigmaTriton** [comment]
For my part, I found it pretty useful and bookmarked it but I guess it’s a question of point of view.
