### ISSUE TITLE
Discuss weak ciphers in 1.1.0 ?

### ISSUE THREAD

**Issue by richsalz** [openssl/web#18]
We get asked how to enable weak ciphers.  The FAQ should talk about the compiling flags and the @SECLEVEL thing.

**Comment by nickthetait** [comment]
I'm interested in tackling this task. Seeking a few pointers before actually changing any software...

# The question
How does this sound? "How do I enable weak ciphers?"
To be placed under the "building and testing" subheading.

# The answer
##  Compile time flags
Is something more in depth than use "enable-weak-ssl-ciphers during compilation" needed? Should a link to the install file be included? https://github.com/openssl/openssl/blob/e7a206694451be19432d079691610994473f53b7/INSTALL#L465

## @SECLEVEL=N
Is linking to [this documentation](https://github.com/openssl/openssl/blob/master/doc/man3/SSL_CTX_set_security_level.pod#default-callback-behaviour) sufficient or does it need to be duplicated here or simplified in some way?
They will need to keep N at 1, or am I not understanding something?

## Caveat
Explain to people why this might not be a good long term strategy? Or is it already expected that these users know the risks?

**Comment by richsalz** [comment]
I think a sentence like "Don't do this unless you have to support legacy applications" is worth doing.
The answer you sketched out looks good to me, but seclevel should be zero.
