### ISSUE TITLE
Change heading font size to better fitting

### ISSUE THREAD

**Issue by Wetinee** [openssl/web#21]
When opening the website in mobile devices (like iPhone6 plus or other devices that have got even smaller screen sizes), the heading looks too large and makes itself overflow the screen width. Decrease heading font size maybe a good option. 
<img width="509" alt="screen shot 2560-08-23 at 15 43 04" src="https://user-images.githubusercontent.com/22177001/29604476-3147a5c4-881a-11e7-8048-ecf9df7be2cf.png">

**Comment by richsalz** [comment]
we really should have an image for the logo, not a text/h1 hack.

**Comment by levitte** [comment]
I think a text hack is fine.  How about decreasing the font size by .1em, and adjusting the body > header h2 relocations appropriately?

**Comment by levitte** [comment]
Proposed fix: #22.  Looks sane enough?
