### ISSUE TITLE
Certificate expired for rt.openssl.org

### ISSUE THREAD

**Issue by cpereida** [openssl/web#226]
Hello OpenSSL folks,

While navigating through old content I found that the certificate for rt.openssl.org expired almost a month ago.

```
Issued On	Friday, January 1, 2021 at 10:37:23 PM
Expires On	Thursday, April 1, 2021 at 11:37:23 PM
```

I appreciate if you could take a look at it.

Thanks

**Comment by mspncp** [comment]
The server does not exist anymore, see https://github.com/openssl/openssl/issues/15026#issuecomment-1034001221.
