### ISSUE TITLE
Please don't delete old alpha tarballs

### ISSUE THREAD

**Issue by tiran** [openssl/web#229]
Hi,

ten days ago I added OpenSSL 3.0.0-alpha14 to CPython's pre-commit CI. Our CI just broke because 
https://www.openssl.org/source/openssl-3.0.0-alpha14.tar.gz has been deleted and GH purged our build caches. I haven't had time to update Python 3.8 and 3.9 feature branches.

Please keep older alphas around for a little while longer.

Thanks!

**Comment by mspncp** [comment]
Old releases are moved to https://www.openssl.org/source/old/3.0

There should actually be a rewrite rule such that the original URL keeps working. @levitte ?

**Comment by mattcaswell** [comment]
Hmm. The old URLs should still work...

**Comment by mattcaswell** [comment]
> Old releases are moved to https://www.openssl.org/source/old/3.0

A link to which doesn't seem to appear on the page: https://www.openssl.org/source/old/

**Comment by levitte** [comment]
I think I found it.  See #230

**Comment by tiran** [comment]
Ah, it's ``old/3.0/``. My download script has a fallback which mangles ``3.0.0-alpha15`` to ``old/3.0.0/``

**Comment by mspncp** [comment]
> Ah, it's `old/3.0/`. My download script has a fallback which mangles `3.0.0-alpha15` to `old/3.0.0/`

Yes, [thou shalt count to three, no more, no less](https://www.openssl.org/blog/blog/2018/11/28/version/). ;-)

**Comment by tiran** [comment]
As a Python developer I approve your Monty Python reference! :)

**Comment by tiran** [comment]
Thanks for your assist. I have modified CPython's download and build script in PR https://github.com/python/cpython/pull/25624

**Comment by mspncp** [comment]
It looks like this issue has been fixed by #230 and #232, is that correct @levitte?

**Comment by mspncp** [comment]
> Old releases are moved to https://www.openssl.org/source/old/3.0
>
> There should actually be a rewrite rule such that the original URL keeps working.

@tiran just for the records: in theory, there is no need to check alternative download URLs. Even though the older tarballs are moved to `old/<version>` subfolders, there is a rewrite rule which keeps the original URLs working. Once in a while it seemed to be broken, but currently it works as expected:

https://www.openssl.org/source/openssl-3.0.0-alpha14.tar.gz
