### ISSUE TITLE
3.0 does not appear in the "old" source listings

### ISSUE THREAD

**Issue by mattcaswell** [openssl/web#231]
Navigating to this page there are no links to old 3.0 alpha releases:
https://www.openssl.org/source/old/

However, the releases do exist if you happen to know the right location:
https://www.openssl.org/source/old/3.0/

**Comment by mspncp** [comment]
While adding the 3.0 entry to https://www.openssl.org/source/old it would be good to sort the entries from new to old.

**Comment by levitte** [comment]
> While adding the 3.0 entry to https://www.openssl.org/source/old it would be good to sort the entries from new to old.

Raise an issue, #230 is already merged

**Comment by mspncp** [comment]
Done, see https://github.com/openssl/web/issues/235.
