### ISSUE TITLE
security.txt is 404 but it exists

### ISSUE THREAD

**Issue by iamamoose** [openssl/web#264]
We have .well-known/security.txt in git and it's even in /var/www but it appears as a 404 at https://openssl.org/.well-known/security.txt even before Akamai.  I don't have access to the Apache logs to figure out why.

**Comment by t8m** [comment]
I've fixed that. The apache actually looks into a different directory for the .well-known directory, not the one directly checked out from the repo. But I symlinked the security.txt from the checked out directory there.

**Comment by t8m** [comment]
https://www.openssl.org/.well-known/security.txt is now fine but https://openssl.org/.well-known/security.txt isn't. Perhaps this needs to be somehow cleared from the Akamai cache? @levitte

**Comment by iamamoose** [comment]
it's caught up now, looks good. thanks

**Comment by t8m** [comment]
Hmm, I still do not see the https://openssl.org/.well-known/security.txt  to be present.
