### ISSUE TITLE
A new website.

### ISSUE THREAD

**Issue by sejr** [openssl/web#3]
I believe that OpenSSL's website should be rebuilt from the ground up to improve usability and communication. A clean and responsive website could do wonders for involvement in the project from the open source community. I am going to get started on one, but was curious if the community had any interest in a particular language or framework.

One tool I was leaning toward was [Jekyll](http://jekyllrb.com/), as the current site doesn't rely too heavily on dynamic content. Perhaps it is time to change that? Feel free to discuss.

**Comment by mattcaswell** [comment]
This never really went anywhere (at least it hasn't so far), but you might want to look at Rich's blog post on this:
https://www.openssl.org/blog/blog/2014/12/28/website-redesign/

**Comment by richsalz** [comment]
We use octopress for the blog, it would be nice if we didn't need two completely separate installations of things.  Thanks much for looking into this!

**Comment by sejr** [comment]
@mattcaswell that is exactly what I was looking for. Thanks!
@richsalz I agree.
