### ISSUE TITLE
sitemap.txt is out of date

### ISSUE THREAD

**Issue by paulidale** [openssl/web#309]
The [`sitemap.txt`](https://www.openssl.org/sitemap.txt) file includes mention of [`roadmap.html`](https://www.openssl.org/policies/roadmap.html) and [`roadmap_2015-2016.html`](https://www.openssl.org/policies/roadmap_2015-2016.html) under policies, neither of which exists.  The sitemap is available from the website at the bottom of the pages.

All the entries in the sitemap should be verified I suspect.

**Comment by levitte** [comment]
Ah, I see why:

https://github.com/openssl/web/blob/96c3ca79d167dbfdc962b71092f8526fafb6a3f3/Makefile#L215-L217

No dependencies, so if it's already in place (like, from a previous run of `make`), `make` will simply say that:

``` console
$ make sitemap.txt 
make: 'sitemap.txt' is up to date.
```

Furthermore, if a build is done in a fresh checkout, this one is much too early in the list of things to do to be able to generate a complete sitemap:

https://github.com/openssl/web/blob/96c3ca79d167dbfdc962b71092f8526fafb6a3f3/Makefile#L56-L74

**Comment by levitte** [comment]
Proposed fix in #310

**Comment by paulidale** [comment]
Good find, I'd not got there yet.
