### ISSUE TITLE
purge-one-hour should move to openssl/omc-tools, and handle a few arguments

### ISSUE THREAD

**Issue by levitte** [openssl/web#316]
Because our web production is divided into multiple directories (`/docs` and `/blog` are separated from the rest of our web), it should be available as a script separated from openssl/web.git, and should also be made to handle two extra arguments:

-   the base directory (currently hard-coded to `/var/www/openssl`, which misses out on anything /docs or /blog)
-   the corresponding base URL

**Comment by paulidale** [comment]
Why not just purge everything?  It's hardly run often.

**Comment by levitte** [comment]
> Why not just purge everything? It's hardly run often.

On our server, they are produced at different times, and in separate directories.
Documentation is rebuilt any time OpenSSL is updated.

**Comment by levitte** [comment]
This has happened, BTW...  so this should have been closed long ago.
