### ISSUE TITLE
Add to old location of coding guideline a forward pointer/redirect 

### ISSUE THREAD

**Issue by DDvO** [openssl/web#317]
As discussed in https://github.com/openssl/openssl/pull/18015:

The URL of the coding guidelines recently changed
from ~https://www.openssl.org/policies/codingstyle.htm~
https://www.openssl.org/policies/codingstyle.html
to https://www.openssl.org/policies/technical/coding-style.html.

Many search engines and likely also various external web pages still point to the old location.
So some forward pointer, ideally an automatic  redirect or rewrite rule should be placed there.

**Comment by paulidale** [comment]
Could we produce a 301 error code for these relocated pages?

**Comment by levitte** [comment]
See #318

**Comment by DDvO** [comment]
This should be reopened (but as a Committer I can't) 
since #318 did not really fix the issue.

**Comment by DDvO** [comment]
My bad - I had make a copy&paste mistake in the issue description above, 
missing the final `l` in https://www.openssl.org/policies/codingstyle.html.

Sorry for the confusion, closing for good.
