### ISSUE TITLE
Ban all server side includes

### ISSUE THREAD

**Issue by levitte** [openssl/web#325]
Server side includes make it easy to include partial HTML into another web page.

However, it makes things difficult for anyone who's working in our web stuff and wants to verify proper rendering in their work directory (by eyeballing, or by giving the browser the URL `file:///PATH/TO/WORK/DIRECTORY/whatever.html)...

We already have mechanisms in place to include partial files into other files, using [.tt](http://www.template-toolkit.org/) templates.

For example, `index.html` could be renamed `index.html.tt` (or `index.md` to `index.md.tt` if #324 comes through) and replace this:

``` html
<!--#include virtual="/inc/legalities.shtml" -->
```

with this:

```
[% INSERT "./inc/legalities.shtml" %]
```

The inclusion of inc/legalities.shtml would be rendered into index.html directly, leaving the web server with one less inclusion to do later on.

**Comment by levitte** [comment]
@quarckster, @vavroch2010, I *knew* I had an issue around somewhere :wink:

**Comment by paulidale** [comment]
Shouldn't you have typed _branch_ not _issue_?

:grin:

**Comment by levitte** [comment]
I actually do have a couple of branches where I've done this work, at least partially.  It took me a moment to find them, as they are broader branches that include early tries at the conversion to markdown.  But I have a few commits in there to cherry-pick :-)

**Comment by levitte** [comment]
#426 is completed, and working as far as I can tell, so in review

**Comment by arapov** [comment]
has been merged

**Comment by arapov** [comment]
And reverted!

**Comment by arapov** [comment]
Sorry, @levitte. Apparently it wants more work.
