### ISSUE TITLE
Where is Stephen Henson's key?

### ISSUE THREAD

**Issue by autarch** [openssl/web#38]
The downloads page at https://www.openssl.org/source/ says:

    PGP keys for the signatures are available from the  OMC page. Current members that sign releases include Richard Levitte, Stephen Henson and Matt Caswell.

However, there is no listing for Stephen Henson on the OMC page at https://www.openssl.org/community/omc.html. I'm guessing he no longer signs releases.

**Comment by levitte** [comment]
Indeed, he's not part of the team any more, I'm sad to say.  See [this blog entry](https://www.openssl.org/blog/blog/2017/10/24/steve-henson/)

**Comment by mattcaswell** [comment]
So shouldn't we fix the text before closing this issue?

**Comment by autarch** [comment]
Yes, you definitely should ;)

**Comment by levitte** [comment]
Oh, of course!!  That text is definitely wrong either way, we've used a team key for years now...

**Comment by levitte** [comment]
(or?  @mattcaswell, you do sign with the team key, don't you?)

**Comment by levitte** [comment]
submitted the quick fix...

**Comment by kroeckx** [comment]
Matt signs with his own key. We should probably also check if
something like that is mentioned somewhere in the source.

**Comment by levitte** [comment]
> Matt signs with his own key.

Ah ok, then the text was correct after all...  I haven't created a release for a long time, so I forget...

> We should probably also check if something like that is mentioned somewhere in the source.

I checked the top files just now...  could see anything.  A second pair of eyes is appreciated, though.

**Comment by richsalz** [comment]
We should really only have a single team release-signing key.

**Comment by mattcaswell** [comment]
Its also here:
https://github.com/openssl/openssl/blob/master/doc/fingerprints.txt#L21
