### ISSUE TITLE
PGP keys does not list OpenSSL OMC key

### ISSUE THREAD

**Issue by ecnepsnai** [openssl/web#416]
On the source page it lists which OTC members that can sign releases:

> PGP keys for the signatures are available from the [OTC page](https://www.openssl.org/community/otc.html). Current members that sign releases include Richard Levitte, Matt Caswell, Paul Dale, and Tomas Mraz.

However, the latest release for 3.1.2 was signed using the OpenSSL OMC key (`EFC0A467D613CB83C7ED6D30D894E2CE8B3D79F5`), which is not listed on the OTC page: https://www.openssl.org/community/otc.html

I'm not sure if the OTC page should also list the OMC key, or of the sources page should mention it.

**Comment by paulidale** [comment]
The OMC key shouldn't be mentioned there, it's not a key for any OTC members.

The keys that can sign releases are listed in the [doc/fingerprints.txt](https://github.com/openssl/openssl/blob/master/doc/fingerprints.txt) file in each release.

So grab the [**penultimate release**](https://www.openssl.org/source/old/3.1/openssl-3.1.1.tar.gz) and check if the OMC key is listed.  It is, so it is a valid key to sign the latest release.

**Comment by ecnepsnai** [comment]
Thanks @paulidale, would it make more sense for the releases page to like to that signatures file instead of the OMC list when talking about signing keys?

**Comment by paulidale** [comment]
There is a change queued: https://github.com/openssl/web/pull/415

**Comment by ecnepsnai** [comment]
Oh, perfect! Glad to see folks are on top of this. :)
