### ISSUE TITLE
OpenSSL documentation is down (404)

### ISSUE THREAD

**Issue by Smjert** [openssl/web#428]
Hopefully this is the right place, but it seems that almost all the manual pages of the openssl documentation are giving 404.
It works up to here for instance https://www.openssl.org/docs/man1.0.2/man3/, for any version, but then clicking any of the specific links gives 404.

Is there some rebuilding happening and I caught a bad time?

**Comment by mspncp** [comment]
The same happens for the 3.1, 3.0, and 1.1.1 manpages. @levitte can you please take a look?

**Comment by arapov** [comment]
openssl/web#426 was recently merged that could cause it...

**Comment by Smjert** [comment]
Things seems to be back now.

**Comment by mattcaswell** [comment]
Yeah, #426 was reverted.

**Comment by levitte** [comment]
It wasn't the fault of #426, but our automation that didn't perform the last step to convert all the .md files to .html.  It's a final step called `manhtml` that was forgotten...

**Comment by arapov** [comment]
This is good that it is easy to fix. We need this change.
