### ISSUE TITLE
committers.html: outdated e-mail and github links

### ISSUE THREAD

**Issue by mspncp** [openssl/web#44]
In the paragraph [committers.html, L92ff](https://github.com/openssl/web/blob/master/policies/committers.html#L92) there are email links to openssl-team@openssl.org and openssl-dev@openssl.org. Are these still correct? I don't know whether openssl-team still exists, but openssl-dev was certainly abandoned. Which are the correct replacements? openssl-project is not open to other OpenSSL contributors.

Also the github handles @openssl/team and @openssl/dev seem to be outdated.

**Comment by richsalz** [comment]
Fixed wording pushed, thanks.
