### ISSUE TITLE
Sitemap.txt is missing

### ISSUE THREAD

**Issue by thomasthaddeus** [openssl/web#452]
There is no sitemap linked at this [address](https://www.openssl.org/sitemap.txt).

![image](https://github.com/openssl/openssl/assets/92204097/dc6b11f5-8250-4cd4-bab2-b6cf97a41188)

**Comment by vavroch2010** [comment]
Issue was fixed by reworking sitemap.txt generation. Currently we are using xml format and Sitemap link was updated to point to it.
https://www.openssl.org/sitemap.xml - this is correct link now. 
@thomasthaddeus Please have a look if it works for you.

**Comment by thomasthaddeus** [comment]
This issue was resolved by the [address](https://www.openssl.org/sitemap.xml) thank you @vavroch2010
