### ISSUE TITLE
FTP site no longer functional in passive mode (default)

### ISSUE THREAD

**Issue by Bo98** [openssl/web#470]
I'm guessing that the passive mode port range is firewalled on the server:

```console
$ curl -vvv ftp://ftp.openssl.org/source/
*   Trying 34.32.219.160:21...
* Connected to ftp.openssl.org (34.32.219.160) port 21
< 220 (vsFTPd 3.0.5)
> USER anonymous
< 331 Please specify the password.
> PASS ftp@example.com
< 230 Login successful.
> PWD
< 257 "/" is the current directory
* Entry path is '/'
> CWD source
* ftp_perform ends with SECONDARY: 0
< 250-
< 250- OpenSSL Source Distribution Area
< 250- Here you can find all official OpenSSL distribution tarballs.
< 250-
< 250 Directory successfully changed.
> EPSV
* Connect data stream passively
< 229 Entering Extended Passive Mode (|||41239|)
* Connecting to 34.32.219.160 (34.32.219.160) port 41239
*   Trying 34.32.219.160:41239...
** connect to 34.32.219.160 port 41239 failed: Operation timed out
* Failed to connect to ftp.openssl.org port 21 after 75286 ms: Couldn't connect to server
```

I'm guessing this is likely why all the mirrors do not have the latest OpenSSL releases.

**Comment by Bo98** [comment]
`rsync rsync://ftp.openssl.org/openssl-ftp/` also doesn't work, though I can't confirm whether that broke at the same time or if that was discontinued long before.

In any case, FTP definitely stopped working on 2023-12-24 and is still advertised in current release emails: https://mta.openssl.org/pipermail/openssl-announce/2024-March/000298.html

**Comment by quarckster** [comment]
Hi, @Bo98, thank you for pointing out this issue. We decided to shut down our FTP server. Our announcement templates were not updated appropriately. I made a PR to fix this https://github.com/openssl/tools/pull/187

**Comment by quarckster** [comment]
https://github.com/openssl/web/pull/479

**Comment by Bo98** [comment]
Thanks for confirming!

**Comment by quarckster** [comment]
FTP mentions are removed from the web site.
