### ISSUE TITLE
Many previously live endpoints under www.openssl.org are no longer accessible

### ISSUE THREAD

**Issue by maddiemort** [openssl/web#490]
I first noticed this with https://www.openssl.org/source/old/3.2.0/openssl-3.2.0.tar.gz, which now produces the following XML response:

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>
```

But similar or identical errors are returned from many other links, including some of the top Google results for openssl-related search terms:

- https://www.openssl.org/source/
- https://www.openssl.org/source/gitrepo.html
- https://www.openssl.org/blog/blog/archives
- https://www.openssl.org/blog/blog/2023/11/23/OpenSSL32
- https://openssl.org/support/donations.html (this is the donation link from this Git repository)

This is causing problems, such as CI jobs failing when trying to download the [first link](https://www.openssl.org/source/old/3.2.0/openssl-3.2.0.tar.gz).

**Comment by mattcaswell** [comment]
This is a known issue which is actively being worked on at the moment.

**Comment by tom-cosgrove-arm** [comment]
@mattcaswell Can I check you're aware that links such as https://www.openssl.org/community/otc.html and https://www.openssl.org/policies/general-supplemental/platforms.html aren't working either? I presume this is as a result of the new https://openssl-library.org/ domain, and things are just being relocated?

**Comment by t-j-h** [comment]
The download links should all be resolved in terms of all the old source download URLs should redirect correctly now.
If there is a download link that isn't working please add it to the issue so we can look at it and resolve it.

Downloads and documentation links were all meant to have redirections in place so they continue to work. 
Other links were not planned to be preserved and will be looked at individually.

**Comment by mattcaswell** [comment]
> @mattcaswell Can I check you're aware that links such as https://www.openssl.org/community/otc.html and https://www.openssl.org/policies/general-supplemental/platforms.html aren't working either? I presume this is as a result of the new https://openssl-library.org/ domain, and things are just being relocated?

For reference the new location for those things is here:

https://openssl-library.org/about/otc/index.html
https://openssl-library.org/policies/platforms/

**Comment by t-j-h** [comment]
All those links other than https://www.openssl.org/source/ and redirecting now. Thanks for the report.
I'll update ones /source/ is cleanly redirecting too.

**Comment by t-j-h** [comment]
https://www.openssl.org/source/ works now too.
