### ISSUE TITLE
Blog posts are out of sync

### ISSUE THREAD

**Issue by beldmit** [openssl/web#491]
https://openssl-library.org/post/ doesn't have a blog post announcing the upcoming webinars, @nhorman post about issues cleanup and probably something else.

**Comment by arapov** [comment]
@beldmit this one?  https://openssl-library.org/post/2024-05-22-quic-webinar/

**Comment by beldmit** [comment]
@arapov No, the one that became https://openssl-foundation.org/events/event1/

**Comment by arapov** [comment]
Oh, I found it. I will fix it
