### ISSUE TITLE
Inactive OTC members

### ISSUE THREAD

**Issue by paulidale** [openssl/web#492]
I'm flagged as inactive on the OTC member list which isn't true.
Matthias and Hugo are marked as active when they aren't.

https://openssl-library.org/about/otc/index.html

**Comment by t-j-h** [comment]
This has been fixed - a couple of older pages weren't refreshed in the change over for recent updates.
Your status and Matthias and Hugo should now all be accurate.
I've also fixed the broken link reference to the bylaws.
