### ISSUE TITLE
3.2 Notes Page Links to 404 Not Found Changelog

### ISSUE THREAD

**Issue by war59312** [openssl/web#496]
Wasn't sure where to report this, so here it is...

https://openssl-library.org/news/openssl-3.2-notes/

Has a Changelog link (right at the top, as part of More details can be found in the [ChangeLog](https://openssl-library.org/news/openssl-3.2-notes/changelog.html).)  pointing to https://openssl-library.org/news/openssl-3.2-notes/changelog.html which is 404 not found.

**Comment by war59312** [comment]
Oh hell, all the cve links on that page are broken too. All 404.

**Comment by quarckster** [comment]
it should be fixed now
