### ISSUE TITLE
Looks like https://openssl.org is down

### ISSUE THREAD

**Issue by backmeupplz** [openssl/web#6]
https://www.openssl.org is up though. The reason why I'd like to submit this issue is that some of my dependencies in an iOS project point at openssl.org without www.

Is this an issue or should I start transitioning my dependencies (cocoapods) towards www domain name? :)

**Comment by kroeckx** [comment]
It's up for me. But it will just redirect you to www.openssl.org.
So yes, please migrate everything to www.openssl.org

**Comment by backmeupplz** [comment]
@kroeckx While we are at it, looks like one of my dependencies is trying to fetch https://openssl.org/source/openssl-1.0.2h.tar.gz — it is redirected correctly to www domain name, but that source is missing. OpenSSL has probably been updated and this version is no longer out there?

**Comment by backmeupplz** [comment]
I'll copy this issue over to the main OpenSSL repo

**Comment by kroeckx** [comment]
1.0.2l was released today. 1.0.2h is a rather old version that has security issues.
