### ISSUE TITLE
Update sponsors page

### ISSUE THREAD

**Issue by iamamoose** [openssl/web#67]
Update sponsors page to list current sponsors and sync the donations and acks page to better match reality.
[sponsors.diff.txt](https://github.com/openssl/web/files/2286620/sponsors.diff.txt)

**Comment by t-j-h** [comment]
Shouldn't this just be a standard PR to update?

I've reviewed it as an issue and it is approved with a +1 from me.

Thanks,

**Comment by iamamoose** [comment]
it should have been a PR, but I didn't do it that way. thanks.
