### ISSUE TITLE
"strategiy" typo in roadmap

### ISSUE THREAD

**Issue by apjanke** [openssl/web#7]
Typo [in the roadmap page](https://github.com/openssl/web/commit/e42ef50e5b67be76e0a2e0b14d3ec85fdc88d7ec#diff-61d3bdebe4874a70141ac9a44d14be38R288) at line 288 misspells "strategy" as "strategiy".

>  Objective met (2015): We have announced a release strategiy which includes end-of-life and long-term support definitions. Also, our security policy has relevant information.

**Comment by richsalz** [comment]
fixed, to be pushed shortly, thanks.
