### ISSUE TITLE
Webpage/manpages don't show B<> perldoc tags bold

### ISSUE THREAD

**Issue by levitte** [openssl/web#74]
(from openssl/openssl#6803)

The very first CSS rule in `/inc/screen.css` has the style `font: inherit`. This suppresses the effect of all `B<>` perldoc tags that we insert painstakingly into the man pages' source.

**Comment by bbolli** [comment]
My suggestion to resolve this issue is this patch:

```diff
diff screen.css.orig screen.css
--- screen.css.orig
+++ screen.css
@@ -239,11 +239,11 @@ ul ul, ul ol, ol ul, ol ol {
   margin-bottom: 0em;
 }

-strong {
+strong, b {
   font-weight: bold;
 }

-em {
+em, i {
   font-style: italic;
 }
```

The alternative, if possible, is to configure pod2html to emit `<strong>` and `<em>` instead of `<b>` and `<i>` for the `B<>` and `I<>` perlpod codes, respectively. The semantic HTML tags are correctly defined in the CSS.

**Comment by levitte** [comment]
Your suggested CSS change is the easiest path forward right now.  Hacking pod2html, even if easier these days, is still quite an effort to customize, and that's not a high priority, so...

**Comment by bbolli** [comment]
Would you prefer a pull request?

**Comment by levitte** [comment]
That would be nice, thanks :-)
